### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by M-Valentino** [Diegogagan2587/Calculator#1]
`<div class="one"><button type="but">1</button></div>` should be `<div class="one"><button type="button">1</button></div>` 

There are some elements that have a unique id and a unique class, but only the class for the element is styled. For those you probably you want to just style based off of the id and remove the class.

This is a good functional calculator. I actually used the source code, changed the styling, and put in one of my projects:
https://github.com/M-Valentino/sacredOS

**Comment by Diegogagan2587** [comment]
@M-Valentino Thanks for pointing that out, I haven't worked on this one for a while, so it would be great to update this project to match my current skills, thanks!

I'll work on this tomorrow.

**Comment by M-Valentino** [comment]
You're welcome
